sudo: required
services:
  - docker

before_install:
  - docker build -t stewarts2008/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true stewarts2008/docker-react npm run test